  CREATE TABLE DEPARTMENT
   (	"DEPT_ID" NUMBER NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DEPT_ID"));
   
   
  CREATE TABLE EMPLOYEE
   (	"EMP_ID" NUMBER NOT NULL ENABLE, 
	"EMP_NAME" VARCHAR2(20 BYTE), 
	"DEPT_ID" NUMBER, 
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMP_ID"));
